feat: add cli argv handling
gemini-testing/create-hermione-app pull request #1
Opened 2022-09-14 16:16 UTC by KuznetsovRoman

2022-09-16 11:49 UTC, DudaGod requested changes
Хочется увидеть тут инфраструктурный PR с заглушками в виде кода. А весь остальной код кусками в следующих PR-ах вместе с тестами.

2022-09-16 11:49 UTC, DudaGod commented on .eslintignore
> +build
Нужно в конце пустую строку добавлять. Это можно в редакторе кода настроить. И в файлах ниже тоже

2022-09-16 11:49 UTC, DudaGod commented on package.json
> +    "README.md"
А зачем readme файл публиковать? Ну и `bin` тоже? Почему бы `bin` не положить в `src`?

2022-09-16 11:49 UTC, DudaGod commented on package.json
> +    "create-hermione-app": "./bin/create-hermione-app"
А здесь указывать `./build/bin/create-hermione-app`

2022-09-16 11:49 UTC, DudaGod commented on .eslintrc.js
> +        browser: true,
А зачем тебе тут браузер?

2022-09-16 11:49 UTC, DudaGod commented on .eslintrc.js
> +    rules: {
И зачем эти пустые опции?

2022-09-16 11:49 UTC, DudaGod commented on .eslintignore
> +build
А где `node_modules` и всякие системные файл - `.*`?

2022-09-16 11:49 UTC, DudaGod commented on .eslintrc.js
> +};
Я бы использовал конфиг вида:
```
module.exports = {
    root: true,
    parser: "@typescript-eslint/parser",
    extends: [
        "gemini-testing",
        "plugin:@typescript-eslint/recommended",
    ],
}
```

И как-то дополнял его при необходимости с помощью `rules`. Пример можешь посмотреть в `hermione-storybook` - https://github.com/gemini-testing/hermione-storybook/blob/master/.eslintrc.js

2022-09-16 11:49 UTC, DudaGod commented on .gitignore
> +/**/.DS_Store
Вот этого я думаю вполне достаточно:
```
node_modules
build
build-spec
.DS_Store
```

2022-09-16 11:49 UTC, DudaGod commented on bin/create-hermione-app
> +require('../build/cli');
А зачем нам этот промежуточный файлик? Мы же можем сразу из ts генерить бинарь.

2022-09-16 11:49 UTC, DudaGod commented on package.json
> +  "scripts": {
Предлагаю скрипты реюзнуть из hermione-storybook - https://github.com/gemini-testing/hermione-storybook/blob/master/package.json.

2022-09-16 11:49 UTC, DudaGod commented on package.json
> +    "start": "./bin/create-hermione-app",
А это зачем? ) Такой командой обычно dev сервер поднимается

2022-09-16 11:49 UTC, DudaGod commented on package.json
> +    "test-unit": "mocha test",
Для юнитов нужно jest использовать

2022-09-16 11:49 UTC, DudaGod commented on package.json
> +}
Не вижу поля `engines` с поддерживаемой версией ноды

2022-09-16 11:49 UTC, DudaGod commented on package.json
> +    "mocha": "^9.2.2",
Мока нам в ts коде не нужна. В ts коде пишем тесты на jest.

2022-09-16 11:49 UTC, DudaGod commented on src/cli.ts
> +import yargs from 'yargs'
Вот этот файлик нужно пометить как `#!/usr/bin/env node` и положить его `src/bin`. Ну и назвать `create-hermione-app`.

2022-09-16 11:49 UTC, DudaGod commented on src/cli.ts
> +import { ToolOpts } from './types/toolOpts'
Где точки с запятыми то?

2022-09-16 11:49 UTC, DudaGod commented on src/cli.ts
> +    .option('default', {
ЧТо это за опция такая? )

2022-09-16 11:49 UTC, DudaGod commented on src/cli.ts
> +    .usage('Usage: $0 <path>')
А зачем тут явно еще писать `Usage:`? При выводе хелпа он вроде бы сам должен добавлять это.

2022-09-16 11:49 UTC, DudaGod commented on src/cli.ts
> +    .demandCommand(1, "Please provide project path")
Не понял для чего еще какую-то команду указывать? У тебя `project path` же должен быть опцией, а не командой.

2022-09-16 11:49 UTC, DudaGod commented on src/index.ts
> +});
А почему ты эти обработчики тут описал? А не в `cli` файле? У тебя же до вызова этого модуля из `cli` может не дойти.

2022-09-16 11:49 UTC, DudaGod commented on src/cli.ts
> +const argvOpts = optsFromArgv(argv as ToolArgv)
У yargs для этого удобный метод должен быть

2022-09-16 11:49 UTC, DudaGod commented on src/types/toolArgv.ts
> +export interface ToolArgv {
Зачем для этого отдельный файл заводить? Ну и часть опций явно же из yargs приезжает.

2022-09-16 11:49 UTC, DudaGod commented on src/cli.ts
> +import _defaults from 'lodash/defaults'
Зачем так то? Импорт просто `lodash` и выдирай из него метод нужный. Мы же пилим не frontend для которого нужно максимально бороться за каждый лишний байт.

2022-09-16 11:49 UTC, DudaGod commented on src/cli.ts
> +launcher.run((defaultOpts) => _defaults({}, argvOpts, defaultOpts) as ToolOpts);
А зачем теперь первым аргументом в `_defaults` объект передавать? Тебе же `argvOpts` больше тут не для чего не нужно. Можем его смело модифицировать.

2022-09-16 11:49 UTC, DudaGod commented on src/index.ts
> +const run = async (createOpts: (defaultOpts: Partial<ToolOpts>) => ToolOpts) => {
Под коллбек обычно отдельный тип описывается. Можно прям в этом же файле.

2022-09-16 11:49 UTC, DudaGod commented on src/cli.ts
> +launcher.run((defaultOpts) => _defaults({}, argvOpts, defaultOpts) as ToolOpts);
А как у тебя тут будет `defaultOpts` доопределять `argvOpts`? Я к тому, что `_defaults` не доопределит какой нубидь массивчик например. Или ты это позже все переделываешь?

2022-09-16 11:49 UTC, DudaGod commented on src/types/toolOpts.ts
> +export interface PluginPrompt {
Тоже не понял для чего ты это тут описываешь. Оно же не юзается нигде.

2022-09-16 11:52 UTC, DudaGod commented on tsconfig.json
> +      "allowJs": true,
Воу. Зачем нам такая опция?

2022-09-16 11:52 UTC, DudaGod commented on tsconfig.json
> +      "checkJs": false,
И такая не нужна.

2022-09-16 11:52 UTC, DudaGod commented on tsconfig.json
> +}
Я бы заюзал конфиг как в hermione-storybook - https://github.com/gemini-testing/hermione-storybook/blob/master/tsconfig.json

2022-09-16 12:08 UTC, KuznetsovRoman commented on package.json
> +    "README.md"
> Зачем readme публиковать?

В таком случае, насколько я помню, в IDE от JetBrains наведении на пакет в импорте показывается эта readme

[Взял за пример package.json этого репо](https://github.com/gemini-testing/hermione-oauth/blob/master/package.json#L8)

> Почему бы bin не положить в src?

В src хранятся ts файлы, не хочется, чтобы ts на него смотрел
[Сделал как в hermione](https://github.com/gemini-testing/hermione)

2022-09-16 12:10 UTC, KuznetsovRoman commented on .eslintignore
> +build
<img width="835" alt="image" src="https://user-images.githubusercontent.com/54893992/190635767-a5fd8613-0a85-4b19-a852-82ab117c3516.png">

2022-09-16 12:16 UTC, KuznetsovRoman commented on src/types/toolArgv.ts
> +export interface ToolArgv {
> Зачем для этого отдельный файл заводить?

А куда его? 

> Часть опций явно из yargs приезжает

Но при этом ts не может его нормально типизировать, и без этого интерфейса видит yargv как промис

2022-09-16 12:40 UTC, KuznetsovRoman commented on src/cli.ts
> +import { ToolOpts } from './types/toolOpts'
Хотел потом линтер запустить, а пока этим не заниматься

2022-09-16 12:41 UTC, KuznetsovRoman commented on src/cli.ts
> +    .option('default', {
"Ничего не спрашивай, все настройки - по умолчанию"

2022-09-16 12:48 UTC, KuznetsovRoman commented on src/cli.ts
> +    .usage('Usage: $0 <path>')
Может, будет добавлять, если использовать команды, но так - точно нет.

2022-09-16 12:53 UTC, KuznetsovRoman commented on src/cli.ts
> +    .demandCommand(1, "Please provide project path")
Без .demandCommand с неуказанным путем он валится с TypeError во внутренней логике
С .demandCommand выводит опции и сообщает о необходимости дать путь. demandCommand можно еще вот так использовать, чтобы сказать, что тебе нужно N аргументов: [Ссылка на доку](https://yargs.js.org/docs/#api-reference-demandcommandmin1-minmsg)

2022-09-16 12:58 UTC, KuznetsovRoman commented on src/index.ts
> +});
Может, но:

1. В `cli.ts` ничего выкидывающую ошибку нет, он просто берет аргументы из командной строки и передает ее в index. Если передать плохие параметры, то yargs сообщит об этом и завершит работу, эти обработчики в `cli.ts` ничего не поменяют.
2. main у проекта - как раз `index.js`, если кто-то захочет написать обертку под этот - `cli.ts` запускаться не будет

2022-09-16 13:01 UTC, KuznetsovRoman commented on src/cli.ts
> +const argvOpts = optsFromArgv(argv as ToolArgv)
который и путь срезолвит из переданного аргумента, и вернет нужный интерфейс?

2022-09-16 13:05 UTC, KuznetsovRoman commented on src/cli.ts
> +launcher.run((defaultOpts) => _defaults({}, argvOpts, defaultOpts) as ToolOpts);
> А как у тебя тут будет defaultOpts доопределять argvOpts?
Если понадобится -  есть [_.defaultsDeep](https://lodash.com/docs/4.17.15#defaultsDeep). Пока не надо

2022-09-16 13:06 UTC, KuznetsovRoman commented on src/types/toolOpts.ts
> +export interface PluginPrompt {
Используется в PluginGroup, который используется в ToolOpts
Так вроде удобнее читать. когда везде только первый уровень вложенности.

2022-09-28 13:14 UTC, DudaGod reviewed
Можем все таки инфраструктурный PR реализовать без логики?
Пример инфраструктурного PR-а - https://github.com/gemini-testing/hermione-test-repeater/pull/1/files. Т.е. после такого PR-а версия не выпускается. И сразу следующим присылается основная логика.

2022-09-28 13:14 UTC, DudaGod commented on package.json
> +        "README.md"
А зачем `readme` пушить?

2022-09-28 13:14 UTC, DudaGod commented on package.json
> +        "dev": "ts-node --compilerOptions {\"noUnusedLocals\":false,\"noUnusedParameters\":false} src/cli.ts ../",
А это зачем? И зачем в нем опции подменять?

2022-09-28 13:22 UTC, KuznetsovRoman commented on package.json
> +        "README.md"
Отвечал выше, продублирую: 

> Зачем readme публиковать?

В таком случае, насколько я помню, в IDE от JetBrains наведении на пакет в импорте показывается эта readme

[Взял за пример package.json этого репо](https://github.com/gemini-testing/hermione-oauth/blob/master/package.json#L8)

2022-09-28 18:58 UTC, KuznetsovRoman commented on package.json
> +        "dev": "ts-node --compilerOptions {\"noUnusedLocals\":false,\"noUnusedParameters\":false} src/cli.ts ../",
В процессе разработки часто приходилось запускать проект, чтоб посмотреть "как оно работает"
ts-node позволяет запускать сразу ts-ные файлы, так чтоб ручками не приходилось их собирать в JS. Только вот когда хочется просто запустить и посмотреть, как оно работает, он начинает плеваться ошибками: "Неиспользованная переменная / Неиспользованный параметр". Вот если подменить опции на эти, то в результате получим возможность легко дебагать проект.

2022-11-21 17:00 UTC, merged