feat: roll out beta version
gemini-testing/create-hermione-app pull request #5
Opened 2022-09-28 02:15 UTC by KuznetsovRoman

2022-10-13 13:28 UTC, KuznetsovRoman reviewed
## Что сделано
Архитектура инструмента такая:
CLI берет у юзера аргументы запуска, обрабатывает их в `toolOpts` и передает в `index.ts`
`index.ts` можно заимпортить в стороннем проекте для модификации поведения этого инструмента. Подробнее о передаваемых/принимаемых аргументах описал ниже.

Инструменту можно передавать путь как до несуществующей директории, так и до директории с уже развернутым проектом (если в нем еще нет гермионаКонфига)

## Принятые решения
Добавил возможность писать комментарии в конфиг, пишутся либо как поле объекта, называющееся `__comment[число]` либо как элемент массива, являющийся строкой вида "__comment[число]:  [текст комментария]". Сделал это, так как пользователю будет удобно из конфига перейти в гит репо, и почитать подробнее про плагин, который установился.

## Контекст

src/plugins-config и src/constants/pluginsGroups можно не ревьюить, там просто хранилище дефолтных конфигов под разные плагины + комментарии (в каждом плагинКонфиге есть ссылка на его гит репо)

2022-10-13 13:28 UTC, KuznetsovRoman commented on src/constants/defaultGeneralPrompts.ts
> +];
Вопросы, задаваемые пользователю в самом начале при запуске программы
При наличии поля `default`, использует его значение в режиме запуска "по умолчанию"

2022-10-13 13:28 UTC, KuznetsovRoman commented on src/constants/defaultToolOpts.ts
> +};
Это для того, чтобы в будущем было удобнее менять конфиг извне, не завязываясь на том, что менять можно исключительно плагины и их настройки

2022-10-13 13:28 UTC, KuznetsovRoman commented on src/index.ts
> +}
Аргументы для модификации инструмента извне

`createOpts`, `createBaseConfig`, `createPluginsConfig` - коллбэки, дающие как аргумент defaultOpts, defaultHermioneConfig и pluginsConfig соответственно, и ожидающие их модифицированные значения как возвращаемое значение.

`generalPromts` позволяет перед настройкой плагинов задать пользователю еще какие то вопросы, и обработать их как нужно. В handler передаются: конфиг hermione и объект с ответами на вопросы из prompts, возвращать нужно так же модифицированный конфиг hermione

Разница между `createOpts`, `createBaseConfig` в том, что createBaseConfig создает изначальный конфиг, к которому затем применяются операции из createOpts. Предполагается, что `createOpts` нужно получать из CLI.

2022-10-13 13:28 UTC, KuznetsovRoman commented on src/index.ts
> +    configNotes.forEach(note => console.log(note));
Не все плагины работают в режиме `plugAndPlay`, каким-то нужна дополнительная настройка. Вот эта строчка выводит напоминания о том, какие плагины нужно поднастроить, и как именно. Более подробно об этом будет написано в сгенерированном конфиге

2022-10-13 13:28 UTC, KuznetsovRoman commented on src/plugins.ts
> +    };
Плагины разбиты на `pluginGroups`, каждая из которых решает определенную задачу. Вот этой функцией собираем индексы групп плагинов, в которых есть плагины, включенные по умолчанию

2022-10-13 13:28 UTC, KuznetsovRoman commented on src/utils.ts
> +        });
Тут надо бы подумать о нормальном выборе версии, использовать "какую-то" - так себе решение

2022-10-17 13:05 UTC, xrsd commented on src/constants/pluginGroups/miscGroup.ts
> +            description: "Only runs specified tests in specified browsers",
Может, `in provided browsers`? А то `specified ... in specified ...`

2022-10-17 13:05 UTC, xrsd commented on src/constants/pluginGroups/reportsGroup.ts
> +    description: "Generate reports about tests, plugins, their performance",
`about tests` – отчеты о тестах – речь же идет о _запусках_ тестов, а не о самих тестах.

Может, как-то переформулировать (?)

2022-10-17 13:05 UTC, xrsd commented on src/constants/pluginGroups/reportsGroup.ts
> +            description: "Displays information about passed and failed tests, shows assertView diffs",
`Shows passed/failed tests, screenshot diffs, error messages, stacktraces, meta-info and so on`.

`assertView diffs` – выглядит как ненужная техническая детализация.

2022-10-17 13:05 UTC, xrsd commented on src/constants/pluginGroups/unstableGroup.ts
> +            description: "Makes assertView comparison less strict",
`Makes screenshot comparison by assertView less strict`.

2022-10-17 13:05 UTC, xrsd commented on src/fsUtils.ts
> +export const isExist = (path: string): Promise<boolean> =>
Странно видеть `is` и глагол следом. Почему не просто `exists`?

2022-10-17 13:05 UTC, xrsd commented on src/fsUtils.ts
> +            .lstat(path)
Ты используешь `lstat`, то есть, если путь – это символическая ссылка на папку, то код скажет, что это не директория.

2022-10-17 13:05 UTC, xrsd commented on src/index.ts
> +    generalPromts?: {
`generalPrompts` – `p` [пропустил](https://translate.yandex.ru/?lang=en-ru&text=prompt)

2022-10-17 13:05 UTC, xrsd commented on src/index.ts
> +}
> createBaseConfig создает изначальный конфиг, к которому затем применяются операции из createOpts.

Тогда, если приоритет такой, то лучше и параметры в таком же порядке перечислять в объекте. Сейчас выглядит так, как будто их порядок определяется их длиной, а не логикой.

2022-10-17 13:05 UTC, xrsd commented on src/index.ts
> +    const pluginsConfig = createPluginsConfig ? createPluginsConfig(defaultPluginsConfig) : defaultPluginsConfig;
Здесь то же самое. Если `opts` бессмысленны без наличия базового конфига, то их стоит создавать уже после того, как создан базовый конфиг.

Логичность такого решения можно еще промоделировать на примере, когда внутри функции летит ошибка. Если ты еще не создал базовый конфиг, а уже роняешь скрипт на стадии создания каких-то опций, то это выглядит как очень странный кейс.

2022-10-17 13:05 UTC, xrsd commented on src/index.ts
> +    }
Кажется, этот код можно было бы сделать более простым, обойдясь одним вызовом `handleGeneralQuestions` и разрулив остальное на уровне аргументов.

И еще: название `defaultGeneralPrompts` выглядит так, как будто если вопросов нет, то тогда будут заданы эти (по умолчанию), но ведь, насколько я понимаю, это не совсем `default`, а скорее `basePrompts` – типа основные вопросы, ответы на которые нам нужны?

2022-10-17 13:05 UTC, xrsd commented on src/index.ts
> +    }
А если оставлять такой подход в виде вызова N функций, каждая из которых обрабатывает/дополняет конфиг, то напрашивается паттерн в виде чейнинга, когда функция возвращает ссылку на объект-конфиг и ты чейнишь один вызов за другим.

Лично меня смущает переменная `hermioneConfig`, которую приходится постоянно передавать внутрь функции, и потом перезаписывать ее сверху.

2022-10-17 21:19 UTC, xrsd commented on src/package.ts
> +            const isLockfileExist = await fsUtils.isExist(path.resolve(dirPath, PMS[pm].lock));
`doesLockfileExist`, `fsUtils.exists`

2022-10-17 21:19 UTC, xrsd commented on src/package.ts
> +            },
Почему не тернарник?

```
(error, stdout, stderr) => error ? reject(stderr) : resolve(stdout),
```

2022-10-17 21:19 UTC, xrsd commented on src/fsUtils.ts
> +export const isDirectory = async (path: string): Promise<boolean | null> => {
Так себе api: по названию должен возвращать `boolean`, а возвращает 3 варианта значения – true/false/null, что вообще не очевидно из самого названия.

2022-10-17 21:19 UTC, xrsd commented on src/package.ts
> +
Выше написал коммент про `isDirectory`. Я бы переделал эту логику – выглядит запутанно.

Если дали путь, и путь не существует, то должен быть `false` и тогда мы создаем папку. А если путь вроде как существует, а нам подсунули не директорию, то нужно изнутри `isDirectory` кидать exception, если уж мы оставляем такое название функции.

2022-10-17 21:19 UTC, xrsd commented on src/package.ts
> +                    spinner.succeed("Hermione and plugins installed successfully");
`have been installed`, по идее

2022-10-17 21:19 UTC, xrsd commented on src/plugins-config/hermione-global-hook.ts
> +        __comment1: 'Add "beforeEach" function, it will be runned before each test',
`run`, `ran`, `run`, не `runned`

2022-10-17 21:19 UTC, xrsd commented on src/plugins-config/hermione-global-hook.ts
> +        __comment1: 'Add "beforeEach" function, it will be runned before each test',
Но если это содержимое конфига, то я бы еще добавил сами функции, а комменты написал прямо внутри, а не оставлял это пользователю. Если он захочет эти функции как-то зарекваирить или что-то еще накрутить, то накрутит, но по умолчанию почему бы ему не получить уже готовый шаблон для этих функций?

2022-10-17 21:19 UTC, xrsd commented on src/plugins-config/hermione-headless-chrome.ts
> +    });
Как вариант, можно было через `lodash` написать:
```
_.mergeWith(config, {
    browsers: {
       'chrome-headless': {
            automationProtocol: "devtools",
            desiredCapabilities: {
                browserName: "chrome",
            },
        }
    },
    sets: {
        desktop: {
            browsers: ['chrome-headless']
        }
    }
}, (objValue, srcValue) => _.isArray(objValue) ? objValue.concat(srcValue) : undefined);
```

2022-10-17 21:19 UTC, xrsd commented on src/plugins-config/hermione-image-minifier.ts
> +        compressionLevel: 2,
В конфиге можно было бы добавить коммент после двойки:

```
set value from 0 (zero compression, fast) to 7 (max compression, slow)
```

2022-10-17 21:19 UTC, xrsd commented on src/plugins-config/hermione-tabs-closer.ts
> +        __comment1: 'Add property "browsers" with reges value like "browsers": /chrome/',
`regexp` или `regex`, у тебя `reges`

2022-10-17 21:19 UTC, xrsd commented on src/plugins-config/hermione-test-filter.ts
> +        __comment2: "With following structure:",
`With the following structure:`

2022-10-17 21:19 UTC, xrsd commented on src/plugins-config/hermione-test-repeater.ts
> +        enabled: true,
Этот плагин нельзя по умолчанию включать, иначе у пользователя будут всегда по 5 раз прогоняться тесты. Либо если ты его делаешь включенным по умолчанию, как это и сделано в самом плагине, то тогда надо оставить `repeat: 0`

https://github.com/gemini-testing/hermione-test-repeater/blob/master/lib/index.js#L27

То есть либо, либо.

2022-10-17 21:30 UTC, xrsd commented on src/utils.ts
> +        return plugin.substring(0, plugin.length - 7);
```
return plugin.substring(0, plugin.length - "/plugin".length);
```
вместо магической константы и ниже с `/hermione` аналогично.

2022-10-19 14:47 UTC, sipayRT requested changes

2022-10-19 14:47 UTC, sipayRT commented on src/bin/create-hermione-app.ts
> +    .demandCommand(1, "Please provide project path")
нужна запятая после `Please`

2022-10-19 14:47 UTC, sipayRT commented on src/constants/defaultGeneralPrompts.ts
> +const defaultGeneralPrompts: GeneralPrompt[] = [
сюда можно сразу добавить вопрос про baseUrl

2022-10-19 14:47 UTC, sipayRT commented on src/constants/defaultHermioneConfig.ts
> +            automationProtocol: "devtools",
здесь нужно коммент добавить что это такое

2022-10-19 14:47 UTC, sipayRT commented on src/constants/packageManagement.ts
> +        install: "install --save-dev",
тут еще не будет лишним `--save-exact`, чтобы не трогать остальные зависимости в lock-файле

2022-10-19 14:47 UTC, sipayRT commented on src/constants/packageManagement.ts
> +        lock: "package-lock.json",
для чего нам здесь нужен lock-файл?

2022-10-19 14:47 UTC, sipayRT commented on src/bin/create-hermione-app.ts
> +        alias: "d",
привычнее было бы опцию `-y` (yes) добавить

2022-10-19 14:47 UTC, sipayRT commented on src/constants/defaultHermioneConfig.ts
> +                browserName: "chrome",
по стандарту ты тут обязан и версию указать. иначе будет ошибка при запросе сессии. Поэтому, в общие вопросы нужно спросить какую версию браузера установить

2022-10-19 14:47 UTC, sipayRT commented on src/constants/pluginGroups/reportsGroup.ts
> +            description: "Profiles another plugins",
Profiles plugins performance

2022-10-19 14:47 UTC, sipayRT commented on src/package.ts
> +
или просто заюзать [ensureDir](https://github.com/jprichardson/node-fs-extra/blob/HEAD/docs/ensureDir.md) из fs-extra

2022-10-19 14:47 UTC, sipayRT commented on src/plugins-config/hermione-safari-commands.ts
> +    _.set(config, "browsers.safari13", {
не нужно в название браузера зашивать его версию

2022-10-19 14:47 UTC, sipayRT commented on src/plugins-config/hermione-safari-commands.ts
> +        meta: { platform: TOUCH_PHONE },
это лишнее

2022-10-19 14:47 UTC, sipayRT commented on src/plugins-config/hermione-test-repeater.ts
> +        enabled: true,
нужно точно отключать. он легко включается опцией из cli

2022-10-19 14:47 UTC, sipayRT commented on src/plugins-config/html-reporter.ts
> +        defaultView: "all",
я бы еще добавил `diffMode: '3-up-scaled'`

2022-10-19 14:47 UTC, sipayRT commented on src/constants/pluginGroups/unstableGroup.ts
> +import { PluginGroup } from "../../types/toolOpts";
название `unstableGroup` какое-то несчастное. лучше уже stabilityGroup. А то сейчас какая-то нестабильная группа, как будто плагины еще в разработке

2022-10-19 14:47 UTC, sipayRT commented on src/fsUtils.ts
> +    return fs.promises.writeFile(pathResolve(dirPath, HERMIONE_CONFIG_NAME), configData);
вот тут уже ощущается связь с другим модулем, который заранее проверил, что текущая директория существует. И функция в итоге не самодостаточная - мы здесь упадем, если на fs не будет указанной директории. Лучше использовать тот же [ensureFile](https://github.com/jprichardson/node-fs-extra/blob/master/docs/ensureFile.md) из fs-extra прямо здесь

2022-10-19 14:47 UTC, sipayRT commented on src/index.ts
> +    configNotes.forEach(note => console.log(note));
console.log → console.info

2022-10-19 14:47 UTC, sipayRT commented on src/package.ts
> +            const isLockfileExist = await fsUtils.isExist(path.resolve(dirPath, PMS[pm].lock));
а зачем вообще пытаться самому понять какой pm использует пользователь? тем более, lock-файла может не быть на fs.
можно же просто дать пользователю возможность выбрать необходимый pm (как ты и делаешь ниже) и вообще избавиться от логики самостоятельного определения

2022-10-19 14:47 UTC, sipayRT commented on src/package.ts
> +    if (noQuestions) {
эм... а почему мы сначала пошли вычислять pm и только после этого решили проверить noQuestions? почему не наоборот?

2022-10-19 14:47 UTC, sipayRT commented on src/plugins-config/index.ts
> +export default pluginsConfig;
давай плагины хранить в виде объекта с полями `name` и `fn`. В таком случае тебе не нужно будет здесь такую свалку импортов создавать

2022-10-19 14:47 UTC, sipayRT commented on src/plugins-config/url-decorator.ts
> +        __comment: "https://github.com/gemini-testing/hermione-url-decorator",
а почему мы именно этот плагин ставим, а не https://github.com/gemini-testing/url-decorator?

2022-10-19 14:47 UTC, sipayRT commented on src/utils.ts
> +                version: "phone-67.1",
у внешних пользователей нет такой версии браузера :) 
я уже выше писал, что при добавлении браузера нужно явно спрашивать про версию

2022-10-19 16:04 UTC, KuznetsovRoman commented on src/package.ts
> +            const isLockfileExist = await fsUtils.isExist(path.resolve(dirPath, PMS[pm].lock));
Удобно же: в ситуации, когда у пользователя уже есть какой-то проект, и он использует, допустим, yarn, если он захочет просто установить гермиону с дефолтным конфигом, то при запуске в режиме по умолчанию, она поставится именно yarn'ом. Да и без флага "По умолчанию": если какой-то проект уже есть, зачем спрашивать про пакетный менеджер, если его можно и самому определить?

lock-файла может не быть на fs
Тогда просто переменная packageManager будет undefined, и вопрос зададим (если нет флага noQuestions, конечно)

Этот кусок - не какая-то ключевая часть, просто, кмк, позволит чуток улучшить UX

2022-10-19 16:05 UTC, KuznetsovRoman commented on src/package.ts
> +    if (noQuestions) {
Хотел сделать так:
1) Если проект существует, и по его лок файлу можно понять, какой пакетный менеджер используется, то его и используем, вряд ли пользователь выберет что-то другое;
2) Если понять, какой используется пакетный менеджер нельзя, то смотрим на флаг "По умолчанию": если он есть, возвращаем дефолтный, если нет - спрашиваем.

Если мы будем сначала смотреть на noQuestions, то в существующем проекте, где используется `yarn`/`pnpm`, с флагом "По умолчанию" пакеты поставятся с помощью `npm`

2022-10-20 19:40 UTC, KuznetsovRoman commented on src/package.ts
> +
Переделал функцию под `ensureDirectory`

2022-10-20 19:51 UTC, KuznetsovRoman commented on src/plugins-config/hermione-global-hook.ts
> +        __comment1: 'Add "beforeEach" function, it will be runned before each test',
Я думал над возможностью вставлять всякие регулярки/функции, но решил, что это небезопасно.

Прикольчики с заменой полей на комментарии - безопасны, потому что нельзя из этих комментариев вырваться: сначала ставится "//" - потом то, что в конфиге.

Если сделать возможность вставлять функции/регулярки, то это открытая `Command Injection`. Насколько это допустимо - обсуждаемый вопрос

2022-10-20 20:01 UTC, KuznetsovRoman commented on src/utils.ts
> +        return plugin.substring(0, plugin.length - 7);
Вынес в constants/packageManagement.ts массивом строк

2022-10-20 20:12 UTC, KuznetsovRoman commented on src/constants/packageManagement.ts
> +        install: "install --save-dev",
> чтобы не трогать остальные зависимости

А как от отсутствия `--save-exact` меняются остальные зависимости в lock-файле?

По доке, разве что устанавливаемые пакеты в `package.json` будут установлены с версией "X.Y.Z", а не "^X.Y.Z"

2022-10-20 20:14 UTC, KuznetsovRoman commented on src/constants/packageManagement.ts
> +        lock: "package-lock.json",
Чтобы иметь возможность определить, какой пакетный менеджер используется в существующем проекте, и не задавать лишнего вопроса. По-моему, чуток улучшает UX

2022-10-20 20:17 UTC, KuznetsovRoman commented on src/constants/defaultHermioneConfig.ts
> +                browserName: "chrome",
По какому стандарту? У меня в тестовом проекте такой конфиг, все работает.

2022-10-20 20:30 UTC, KuznetsovRoman commented on src/plugins-config/url-decorator.ts
> +        __comment: "https://github.com/gemini-testing/hermione-url-decorator",
Используется он, ссылка кривая

Потом только заметил, что тот - deprecated, и вот ссылку забыл обновить

2022-10-20 22:38 UTC, KuznetsovRoman commented on src/constants/pluginGroups/reportsGroup.ts
> +    description: "Generate reports about tests, plugins, their performance",
`Generate reports about tests' results, plugins, their performance`

2022-10-21 10:17 UTC, KuznetsovRoman commented on src/constants/defaultHermioneConfig.ts
> +            automationProtocol: "devtools",
"Что такое протокол автоматизации?"

2022-10-25 08:18 UTC, KuznetsovRoman commented on src/plugins-config/index.ts
> +export default pluginsConfig;
Уточню: предлагаешь сделать так, чтоб файлы из `src/plugins-config/hermione-*.ts` экспортили объект?

2022-11-01 14:41 UTC, sipayRT commented on src/constants/packageManagement.ts
> +        install: "install --save-dev",
хм, раньше эта опция еще и старалась вносить как можно меньше правок. Типа, если у гермионы по крышке какой-то пакет приезжает, то для остальных зависимостей версия пакета не изменялась (несмотря на то, что можно было пару миноров апнуть)

2022-11-21 13:49 UTC, sipayRT approved these changes

2022-11-21 13:49 UTC, sipayRT commented on src/constants/pluginGroups/reportsGroup.ts
> +    description: "Generate reports about tests' results, plugins, their performance",
че это за кавычка повисла?

2022-11-21 13:49 UTC, sipayRT commented on src/constants/pluginGroups/index.ts
> +const pluginsGroup: PluginGroup[] = [browsersGroup, reportsGroup, stabilityGroup, miscGroup];
если мы reportGroup по умолчанию включаем, то он должен идти первым

2022-11-21 13:49 UTC, sipayRT commented on src/constants/pluginGroups/browsersGroup.ts
> +    description: "Add different browser support (mobile hermione, headless-chrome)",
что за "mobile hermione"? :) 
может mobile emulation?

2022-11-21 17:00 UTC, merged