types: fix exporting types
gemini-testing/create-hermione-app pull request #7
Opened 2022-12-09 02:32 UTC by KuznetsovRoman

2022-12-09 09:21 UTC, DudaGod requested changes
Похоже, что пока с типами работать не очень удобно. Предлагаю поправить.

2022-12-09 09:21 UTC, DudaGod commented on package.json
> +    },
Можешь еще раз объяснить для чего все эти `exports` и `typesVersions`?

Удобное использование типов это когда пишешь вот так:
```
import type {foobar} from "create-hermione-app";
```

Ну или покажи на примере как пользователь будет использовать типы в твоем случае.

2022-12-09 09:21 UTC, DudaGod commented on package.json
> +        "./types/hermioneConfig": "./build/types/hermioneConfig.js",
Типы от этого файла вообще должны быть прямо в hermione же

2022-12-09 09:21 UTC, DudaGod commented on package.json
> +        "./types/pluginsConfig": "./build/types/pluginsConfig.js",
Эти типы тоже должны быть в hermione

2022-12-09 09:21 UTC, DudaGod commented on package.json
> +        "./types/toolArgv": "./build/types/toolArgv.js",
А для чего это экспортировать?

2022-12-09 09:21 UTC, DudaGod commented on package.json
> +        "./types/toolOpts": "./build/types/toolOpts.js"
А это должно по идее инклюдится в общем `d.ts` файле. Например в lodash инклюдится с помощью `reference` - https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/lodash/index.d.ts.

А в webdriverio используется такой подход - https://github.com/webdriverio/webdriverio/blob/main/packages/webdriverio/src/index.ts#L188. Предлагаю сделать как в wdio.

2022-12-10 15:54 UTC, KuznetsovRoman commented on package.json
> +    },
> Можешь еще раз объяснить, для чего все эти `exports` и `typesVersions`?

Для скрипта-обертки. Без этих экспортов, нельзя будет вытащить много разных типов, которые нам нужны.

> Ну или покажи на примере как пользователь будет использовать типы в твоем случае.

Как-то так:
```ts
import type { GeneralPrompt, HandleGeneralPromptsCallback } from "create-hermione-app/types/toolOpts";
```

2022-12-10 15:54 UTC, KuznetsovRoman commented on package.json
> +        "./types/hermioneConfig": "./build/types/hermioneConfig.js",
Подтянул оттуда

2022-12-10 15:56 UTC, KuznetsovRoman commented on package.json
> +        "./types/pluginsConfig": "./build/types/pluginsConfig.js",
Это не Plugins, а PluginsConfig, такого нет.

```ts
export interface PluginsConfig {
    [plugin: string]: (config: HermioneConfig) => void | Promise<void>;
}

```

2022-12-10 15:56 UTC, KuznetsovRoman commented on package.json
> +        "./types/toolArgv": "./build/types/toolArgv.js",
Убрал

2022-12-10 17:24 UTC, KuznetsovRoman commented on package.json
> +        "./types/toolOpts": "./build/types/toolOpts.js"
Вот первой мыслью у меня как раз и было сделать именно так, но отказался от этой идеи, так как внутри типы начинают импортироваться из `./types/index.ts`, да и в IDE будет неудобно смотреть, что это за тип

2022-12-10 17:48 UTC, KuznetsovRoman commented on package.json
> +        "./types/toolOpts": "./build/types/toolOpts.js"
Исправил, теперь снаружи оно импортируется вот так:

```ts
import createHermioneApp from "create-hermione-app";

import type {
    DefaultOpts,
    GeneralPrompt,
    HandleGeneralPromptsCallback,
    PluginPrompt,
    HermioneConfig,
    CreatePluginsConfigCallback
} from "create-hermione-app";
```

Но внутри теперь vscode предлагает подтягивать типы не только из того места, где они описываются, но еще и из `types/index.ts` и `index.ts`

<img width="592" alt="image" src="https://user-images.githubusercontent.com/54893992/206868388-e16aa029-7a05-4b7e-a7ad-0196faa5288c.png">

2022-12-14 13:46 UTC, DudaGod commented on package.json
> +        "./types/hermioneConfig": "./build/types/hermioneConfig.js",
> Пришлось сделать так, потому что у BrowserConfig нет поля automationProtocol, и у конфига из гермионы все поля required:

Кажется, что это можно было бы сразу в hermione и пофиксить.

2022-12-14 13:46 UTC, DudaGod commented on package.json
> +    },
> import type { GeneralPrompt, HandleGeneralPromptsCallback } from "create-hermione-app/types/toolOpts";

Ну вот выглядит довольно не удобно.

2022-12-14 13:47 UTC, DudaGod commented on package.json
> +        "./types/pluginsConfig": "./build/types/pluginsConfig.js",
Забыли описать видимо. Тоже можно было бы в hermione унести

2022-12-14 13:52 UTC, DudaGod commented on package.json
> +        "./types/toolOpts": "./build/types/toolOpts.js"
> Но внутри теперь vscode предлагает подтягивать типы не только из того места, где они описываются, но еще и из types/index.ts и index.ts

Можно посмотреть на примеры в wdio. Возможно они этот момент как-то разруливают. Но вообще я обычно просто сам руками пишу откуда нужно тип взять.

2022-12-14 13:52 UTC, DudaGod approved these changes
/ok

2022-12-14 22:36 UTC, KuznetsovRoman commented on package.json
> +        "./types/pluginsConfig": "./build/types/pluginsConfig.js",
Это не тот PluginsConfig)

Это словарь *[Название плагина] => [функция, изменяющая `hermioneConfig`]*

*"Как включение плагина вляет на конфиг гермионы"*

2022-12-16 06:00 UTC, merged