docs: add documentation
gemini-testing/create-hermione-app pull request #8
Opened 2022-12-09 02:41 UTC by KuznetsovRoman

2022-12-09 10:43 UTC, xrsd requested changes

2022-12-09 10:43 UTC, xrsd commented on docs/ru/create-hermione-app.md
> +Также может быть использован чтобы добавить [hermione](https://github.com/gemini-testing/hermione) в уже существующий проект.
Если обратишь внимание на описание всех плагинов, которые я переделывал, то там везде идет формулировка, начинающаяся с глагола:

> Используйте `create-hermione-app`, чтобы быстро и удобно настроить гермиону как в новом, так и в уже существующем проекте.

2022-12-09 10:43 UTC, xrsd commented on docs/ru/create-hermione-app.md
> +## Краткий обзор
```
## Использование
```

2022-12-09 10:43 UTC, xrsd commented on docs/ru/create-hermione-app.md
> +## Режим "по умолчанию"
1. Поскольку это подраздел для «Использования», то нужно использовать 3 `#`:

```
### Режим «по умолчанию»
```

2. Надо использовать русские кавычки, у тебя – английские.  Из русских лучше использовать ёлочки: https://www.artlebedev.ru/kovodstvo/sections/104/

2022-12-09 10:43 UTC, xrsd commented on docs/ru/create-hermione-app.md
> +Вы можете добавить аргумент `-y` или `--yes` чтобы запустить инструмент в режиме "без вопросов".
«без вопросов»

На Маке елочки ставятся в русской раскладке сочетаниями:
« – `Option + Shift + =`
» – `Option + =`

2022-12-09 10:43 UTC, xrsd commented on docs/ru/create-hermione-app.md
> +## Список всех предлагаемых плагинов
слово `всех`, кажется, избыточно

2022-12-09 10:43 UTC, xrsd commented on docs/ru/create-hermione-app.md
> +- [hermione-tabs-closer](https://github.com/gemini-testing/hermione-tabs-closer)
Вот тут я бы подумал, сам по себе список плагинов ни о чем не говорит. Где-то конечно пользователь догадается о чем идет речь, но может, имело бы смысл тут как-то подробнее этот список представить:

* [Global Hook](https://github.com/gemini-testing/hermione-global-hook/blob/master/docs/ru/hermione-global-hook.md) – чтобы вынести общую логику из своих тестов в специальные обработчки для _beforeEach_ и _afterEach_ хуков.
* [Plugins Profiler](https://github.com/gemini-testing/hermione-plugins-profiler) – для профилирования плагинов
* [Retry Progressive](https://github.com/gemini-testing/hermione-retry-progressive) – чтобы дополнительно прогонять тесты, если ошибки, с которыми они упали соответствуют заданному набору шаблонов.
* итд

2022-12-09 10:43 UTC, xrsd commented on docs/ru/create-hermione-app.md
> +        // Имя плагина. Инструмент попытается загрузить его выбранным пакетнм менеджером
`пакетным`

2022-12-09 10:43 UTC, xrsd commented on docs/ru/create-hermione-app.md
> +        // Usualy you would want to describe your plugin's default config
В русской версии комментарии лучше тоже писать по-русски. И ниже аналогично.

2022-12-09 10:43 UTC, xrsd commented on docs/ru/create-hermione-app.md
> +*Примечание: в `hermioneConfig` можно класть только сериализуемые данные*
Выглядит слишком лаконично. Речь же идет о создании своего собственного node-js-скрипта на базе `create-hermione-app`? Значит, надо как-то явно это описать. Что вот, вы можете создать свой скрипт для разворачивания конфигурации. Вот вам коллбэки, которые принимают такие аргументы и вы можете сделать в них то-то.

2022-12-09 10:43 UTC, xrsd commented on docs/ru/create-hermione-app.md
> +Если по указанному пути уже имеется проект, инструмент попробует определить используемый пакетный менеджер, и будет использовать его для установки пакетов.
Не хватает примера, а что в итоге будет в терминале после запуска этих команд.

В идеале, это наверное должна быть гифка анимированная, ну или хотя бы несколько скриншотов с экранами терминала, чтобы пользователь заранее представлял себе результат своих действий от запуска программы.

2022-12-09 10:48 UTC, xrsd commented on docs/ru/create-hermione-app.md
> +*Примечание: в `hermioneConfig` можно класть только сериализуемые данные*
И я бы все-таки уточнил кому и когда может понадобиться кастомизировать наш скрипт - типа объяснить, что если у вас есть свои внутренние плагины для гермионы, которые вы распространяется для каких-то проектов внутри компании, то вы можете создать свою версию `create-hermione-app` под свои внутренние реалии.

2022-12-10 20:34 UTC, KuznetsovRoman commented on docs/ru/create-hermione-app.md
> +Вы можете добавить аргумент `-y` или `--yes` чтобы запустить инструмент в режиме "без вопросов".
У меня по-другому:
« – `Option + Ё`
» - `Option + Shift + Ё`

2022-12-15 08:26 UTC, xrsd approved these changes

2022-12-15 08:26 UTC, xrsd commented on docs/en/create-hermione-app.md
> +### Zero questions mode
Это общепринятое выражение `zero questions`?

Если нет, то я бы лучше так и назвал бы `No questions mode`.

2022-12-15 08:26 UTC, xrsd commented on docs/ru/create-hermione-app.md
> +*Примечание: в `hermioneConfig` можно класть только сериализуемые данные*
Точку в конце предложения забыл.

2022-12-15 08:26 UTC, xrsd commented on docs/ru/create-hermione-app.md
> +#### createOpts (обязателен)
Лучше спусти вниз пометку _обязателен_, иначе у тебя пометка в якорь прорастает и безотносительно якоря еще читабельность заголовка ухудшается.

```
Обязательный параметр.

Консольный интерфейс по умолчанию обрабатывает данный путь и аргумент `--yes`.
...
```

2022-12-15 08:26 UTC, xrsd commented on docs/ru/create-hermione-app.md
> +Вы также можете изменить `defaultOpts` Сейчас этот объект имеет ключ `pluginGroups`, по которому определяет, как плагины разбиваются на группы.
```
по которому определяет, как плагины разбиваются на группы.
```

Не очень понятно «кто определяет?». Объект определяет? Скрипт? Как будто у тебя подлежащее потерялось.

2022-12-15 08:26 UTC, xrsd commented on docs/ru/create-hermione-app.md
> +Если у GeneralPrompt не указать значение по умолчанию, вопрос будет задан даже при `noQuestions: true`
`GeneralPrompt` в бэктики не надо завернуть?

2022-12-15 08:29 UTC, xrsd commented on docs/en/create-hermione-app.md
> +Firstly, you need to include your plugin into existing pluginGroup, or create your own:
Если ты ссылаешься на реальный объект, то тогда надо его в бэктики заключать. Если же ты просто пишешь про `plugin group`, то тогда надо обычным языком описывать.

2022-12-16 09:50 UTC, merged